# -*- coding: utf-8 -*-
"""Python Internship Assignment-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqsOm8_MGr5FjlWDOisQzvPCaiSB3vQo

___

<a href='https://viqasys.com/wp-content/uploads/2021/07/ns1.png'><img src='https://viqasys.com/wp-content/uploads/2021/07/ns1.png'/></a>
___
<center><em>Content Copyright VIQASYS INNOVATIONS PVT LTD.</em></center>

# Assignment 3

## Question 1
Write a Python program to create a list with the following elements: 4, 8, 9, 'apple', 'banana', 'cherry'. Print the list.
"""

my_list=[4,8,9,'apple', 'banana', 'cherry']
print(my_list)

"""## Question 2
Given the list [10, 20, 30, 40, 50], write a Python script to print the second and fourth elements.
"""

my_list = [10, 20, 30, 40, 50]

print("Second element:", my_list[1])
print("Fourth element:", my_list[3])

"""## Question 3
Create a list of the first 10 even numbers. Write a Python program to print the first half of the list using slicing.
"""

even_numbers = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
midpoint = len(even_numbers) // 2
first_half = even_numbers[:midpoint]
print("First half of the list:", first_half)

"""## Question 4
Here is a list: ["red", "green", "blue"]. Change the element "blue" to "yellow" and print the updated list.
"""

colors = ["red", "green", "blue"]


colors[2] = "yellow"

print(colors)

"""## Question 5
Start with an empty list. Write a Python program to append 'apple', 'banana', and 'cherry' to the list using separate append calls, then print the list.
"""

fruits = []
fruits.append('apple')
fruits.append('banana')
fruits.append('cherry')
print(fruits)

"""## Question 6
Given two lists, [1, 2, 3] and [4, 5, 6], write a Python script that extends the first list with the second list and prints the updated list.
"""

list1 = [1, 2, 3]
list2 = [4, 5, 6]
list1.extend(list2)
print(list1)

"""## Question 7
Here is a list: [1, 2, 4]. Insert the number 3 at the appropriate position to maintain sorted order and print the list.
"""

my_list = [1, 2, 4]
my_list.insert(2, 3)
print(my_list)

"""## Question 8
From the list [1, 2, 3, 4, 5, 3], write a Python program to remove the first occurrence of the number 3.
"""

my_list = [1, 2, 3, 4, 5, 3]
my_list.remove(3)
print(my_list)

"""## Question 9
Using the list [10, 20, 30, 40, 50], write a Python script to remove and print the last element.
"""

my_list = [10, 20, 30, 40, 50]

# Remove and print the last element
last_element = my_list.pop()
print("Removed element:", last_element)

# Print the updated list
print("Updated list:", my_list)

"""## Question 10
Take the list [1, 2, 3, 4, 5] and write a Python script that empties the list and prints it.
"""

numbers = [1, 2, 3, 4, 5]
numbers.clear()
print(numbers)

"""## Question 11
Write a Python program to find the number of elements in the list [1, 2, 3, 4, 5, 6, 7, 8, 9].
"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(len(numbers))

"""## Question 12
Given the list ['apple', 'banana', 'apple', 'cherry'], count and print how many times 'apple' appears in the list.
"""

fruits = ['apple', 'banana', 'apple', 'cherry']
apple_count = fruits.count('apple')
print(f"Number of times 'apple' appears: {apple_count}")

"""## Question 13
Create a list of the words ['banana', 'apple', 'cherry']. Write a Python program to sort the list alphabetically and print it.
"""

words = ['banana', 'apple', 'cherry']

words.sort()

print(words)

"""## Question 14
Given the list [1, 2, 3, 4, 5], write a script that reverses the list and prints it.
"""

my_list = [1, 2, 3, 4, 5]

my_list.reverse()

print(my_list)

"""## Question 15
Check if the value 'cat' exists in the list ['dog', 'rabbit', 'horse'] and print the result as a boolean value.
"""

animals = ['dog', 'rabbit', 'horse']

cat_exists = 'cat' in animals

print(cat_exists)

"""## Question 16
Copy the contents of list a = [1, 2, 3] into a new list b and print both lists.
"""

a = [1, 2, 3]
b = a.copy()

print("List a:", a)
print("List b:", b)

"""## Question 17
Using list comprehension, create a list of squares for numbers from 1 to 10 and print the list.
"""

squares = [x**2 for x in range(1, 11)]
print(squares)

"""## Question 18
Here is a nested list: [[1, 2], [3, 4], [5, 6]]. Access and print the second element of the first nested list.
"""

nested_list = [[1, 2], [3, 4], [5, 6]]

second_element = nested_list[0][1]
print(second_element)

"""## Question 19
Concatenate the lists [1, 2, 3] and [4, 5, 6] into a single list and print the result.
"""

list1 = [1, 2, 3]
list2 = [4, 5, 6]

combined_list = list1 + list2

print(combined_list)

"""## Question 20
Using a list as a stack, push the elements 10, 20, 30, one by one, and then pop each one in LIFO order, printing each popped element.
"""

stack = []

stack.append(10)
stack.append(20)
stack.append(30)

while stack:
  element = stack.pop()
  print(element)